### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [gillybops/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by gillybops** [comment]
After researching online, I added the following line to my code in .../app/views/layouts/application.html.erb and tested locally and on heroku:=

 <meta name="viewport" content="width=device-width, initial-scale=1">

**Comment by Mikeysax** [comment]
:+1:
